import { CSSProperties, useMemo } from 'react';
import Head from 'next/head';
import { GetServerSideProps, InferGetServerSidePropsType } from 'next';
import { Button, Col, Row, Space, Typography } from 'antd';
import { AlignLeftOutlined, DownloadOutlined, FilterOutlined } from '@ant-design/icons';
import { ChartWrapper } from '@/components/ChartWrapper';

const titleStyles: CSSProperties = {
  margin: 0,
};

const iconStyle: CSSProperties = {
  color: '#00857c',
};

const noteCountStyles: CSSProperties = {
  color: '#9f9f9f',
};

const chartWrapperStyles: CSSProperties = {
  marginTop: '24px',
};

const buttonWrapperStyles: CSSProperties = {
  textAlign: 'right',
};

interface CovidData {
  date: string;
  value: number;
}

const HomePage = ({ data }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const dataLeftSide = useMemo(() => data.splice(0, 6), [data]);
  const dataRightSide = useMemo(() => data.splice(-6), [data]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Row gutter={24} align="middle" justify="space-between">
        <Col span={12}>
          <Typography.Title level={3} style={titleStyles}>
            Page Title
          </Typography.Title>
        </Col>
        <Col span={12} style={buttonWrapperStyles}>
          <Space direction="horizontal" size="large">
            <Button>
              Export to PDF <DownloadOutlined style={iconStyle} />
            </Button>
            <Button>
              Notes&nbsp;<span style={noteCountStyles}>(3)</span>&nbsp;
              <AlignLeftOutlined style={iconStyle} />
            </Button>
            <Button>
              Filter <FilterOutlined style={iconStyle} />
            </Button>
          </Space>
        </Col>
      </Row>

      <Row gutter={24} style={chartWrapperStyles}>
        <Col span={12}>
          <ChartWrapper data={dataLeftSide} title="First 6 weeks" commentCount={3} />
        </Col>
        <Col span={12}>
          <ChartWrapper variant="pie" data={dataRightSide} title="Last 6 weeks" commentCount={9} />
        </Col>
      </Row>
    </>
  );
};

export default HomePage;

export const getServerSideProps: GetServerSideProps = (async context => {
  const res = await fetch(
    'https://api.coronavirus.data.gov.uk/v1/data?filters=areaType=nation;areaName=England&structure={"date":"date","value":"newWeeklyNsoDeathsByRegDate"}',
  );
  const data = await res.json();

  return { props: { data: data.data } };
}) satisfies GetServerSideProps<{
  data: CovidData[];
}>;
